### ISSUE TITLE
Getting "jwt malformed" upon debugging verify token method

### ISSUE THREAD

**Issue by joegitau** [TomDoesTech/REST-API-Tutorial-Updated#1]
Hi Tom, 

For starters, thank you for taking the time to review this issue.

This is related to an issue I have been getting after following your Youtube tutorial - it is related to verification of tokens - whereby upon debugging the verify method, i get an error: `jwt malformed`.

Here is the repo to my project - https://github.com/joegitau/node-typescript-api

**Comment by joegitau** [comment]
Alright. Thanks for taking time to look into this.
I will address that and hopefully I will get it sorted out. 

I just recently subscribed to your channel and overall I was impressed with the manner at which you structure your projects and expound on matters with ease. I can't wait to see more of your tutorials.

**Comment by tomanagle** [comment]
Try this: https://youtu.be/FzKrfwplips
