### ISSUE TITLE
Private and public keys

### ISSUE THREAD

**Issue by kelechinwaji** [TomDoesTech/REST-API-Tutorial-Updated#18]
Hello, the private and public keys are throwing an error `Error: secretOrPrivateKey must be an asymmetric key when using RS256` and 
`Error: secretOrPrivateKey has a minimum key size of 2048 bits for RS256`

**Comment by aurora-721** [comment]
To generate public and private keys you can go to the following website: https://cryptotools.net/rsagen and choose 2048 for the key length. The error that is thrown is because the length of the public and private keys are insufficient.

**Comment by kelechinwaji** [comment]
thank you
