### ISSUE TITLE
Missing DocumentDefinitions export member after removing deprecated @typings/mongoose in favour of built-in typings

### ISSUE THREAD

**Issue by replete** [TomDoesTech/REST-API-Tutorial-Updated#2]
First of all, thanks for this tutorial, I've been using it to learn TypeScript and get back to development after a few years on development hiatus.

I've been working on this codebase, and today just started having a go at implementing Jest, during which I've encountered a few head-scratchers which probably weren't a problem before because the project was using `@types/mongoose` definitions, which were for version 5.11.97, mismatching version 6 of the `mongoose` package used in this project. 

(`@types/mongoose` is now deprecated so this problem will turn up when you remove the package and rely on `mongoose` package's built-in definitions)

![Screen Shot 2021-10-15 at 02 30 27](https://user-images.githubusercontent.com/812139/137417927-9d846403-d037-4d31-bf00-6dcd296cdb4c.png)

My first attempt to resolve was replacing `DocumentDefinition` with `Document`, which creates this error:
![Screen Shot 2021-10-15 at 02 45 19](https://user-images.githubusercontent.com/812139/137419118-802caa5d-62ab-41c8-ad50-c93131936717.png)

Any ideas?

P.S. How's the Jest integration coming on? I was trying to implement Jest with supertest

**Comment by tomanagle** [comment]
I created a video about how to fix this issue: https://youtu.be/5-1KuU-21uI

The testing video has also been out for a few days now: https://youtu.be/r5L1XRZaCR0
