### ISSUE TITLE
postman collection variables.

### ISSUE THREAD

**Issue by kelvinbush** [TomDoesTech/REST-API-Tutorial-Updated#6]
The postman collection variables are not being updated.
The test scripts are trying to update the environment variables.
This should work: `var jsonData = JSON.parse(responseBody);
pm.collectionVariables.set("accessToken", jsonData.accessToken);
pm.collectionVariables.set("refreshToken", jsonData.refreshToken);
console.log(jsonData)`

**Comment by tomanagle** [comment]
Do you have an environment set?

**Comment by kelvinbush** [comment]
No I did not, that's why I had the variables scoped to the collection.
Thanks for the tutorial it is a great resource.
