### ISSUE TITLE
there may be a typo in user.schema.ts

### ISSUE THREAD

**Issue by aliensb** [TomDoesTech/REST-API-Tutorial-Updated#9]
Hi Tom
    in the user.schema.ts line 48 which is the `password` filed validation message , but the message here is "Name is required". I think it maybe a typo,maybe the correct message should be "Password is required"

**Comment by aliensb** [comment]
would you mind if i submit a PR to fix it?

**Comment by tomanagle** [comment]
> would you mind if i submit a PR to fix it?

Yeah, go for it. Nice find
